[global]
  name = "My application"
  [global.environment]
    key = "value"

[hasura]

  [[hasura.jwtSecrets]]
    type = "HS256"
    key = "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"
    issuer = "additional-custom-jwt-secret"

[storage]

[functions]
  [functions.node]
    version = 16

[auth]
  [auth.redirections]
    clientUrl = "http://localhost:3000"
    allowedUrls = []
  [auth.anonymous]
    enabled = true
  [auth.signUp]
    enabled = true
  [auth.roles]
    default = "user"
    allowed = ["user", "me"]
  [auth.email]
    [auth.email.passwordless]
      enabled = true
    [auth.email.verification]
      required = true
    [auth.email.domains]
      allowed = []
      blocked = []
    [auth.email.emails]
      allowed = []
      blocked = []
  [auth.gravatar]
    enabled = true
    default = "blank"
    rating = "g"
  [auth.locale]
    default = "en"
    allowed = ["en", "fr"]
  [auth.password]
    minLength = 3
    [auth.password.hibp]
      enabled = false
  [auth.providers]
    [auth.providers.apple]
      enabled = false
      clientId = ""
      keyId = ""
      privateKey = ""
      scope = ["name", "email"]
      teamId = ""
    [auth.providers.bitbucket]
      enabled = false
      clientId = ""
      clientSecret = ""
    [auth.providers.facebook]
      enabled = false
      clientId = ""
      clientSecret = ""
      scope = ["email", "photos", "displayName"]
  [auth.sms]
    [auth.sms.passwordless]
      enabled = false
    [auth.sms.twilio]
      accountSid = ""
      authToken = ""
      from = ""
      messagingServiceId = ""
  [auth.webauthn]
    enabled = false
    [auth.webauthn.relyingParty]
      name = ""
      origins = []
    [auth.webauthn.attestation]
      timeout = 60000
  [auth.accessToken]
    expiresIn = 900
    [auth.accessToken.customClaims]
      organisation-id = "profile.organisation.id"
  [auth.refreshToken]
    expiresIn = 43200
  [auth.mfa]
    enabled = true
    [auth.mfa.totp]
      issuer = "nhost"

[smtp]
  user = "user"
  password = "password"
  sender = "nhost@example.com"
  host = "mailhog"
  port = 1025
  secure = false
  method = "PLAIN"
