[global]
name = "Nhost application"

[hasura]
jwtSecrets = []

[functions.node]
version = 16
[auth.redirections]
clientUrl = "http://localhost:3000"
allowedUrls = []
[auth.anonymous]
enabled = false
[auth.signUp]
enabled = true
[auth.roles]
default = "user"
allowed = ["user", "me"]
[auth.email.passwordless]
enabled = false
[auth.email.verification]
required = true
[auth.email.domains]
allowed = []
blocked = []
[auth.email.emails]
allowed = []
blocked = []
[auth.gravatar]
enabled = true
default = "blank"
rating = "g"
[auth.locale]
default = "en"
allowed = []
[auth.password]
minLength = 9
[auth.password.hibp]
enabled = false
[auth.sms.passwordless]
enabled = false
[auth.sms.twilio]
accountSid = ""
authToken = ""
from = ""
messagingServiceId = ""
[auth.webauthn]
enabled = false
[auth.webauthn.relyingParty]
origins = []
[auth.webauthn.attestation]
timeout = 60000
[auth.accessToken]
expiresIn = 900
[auth.refreshToken]
expiresIn = 43200
[auth.mfa]
enabled = false
[smtp]
user = ""
password = ""
sender = ""
host = ""
port = 1025
secure = false
method = "PLAIN"
